function wfu_amazons3_authorize_app_start(nonce){document.querySelector(".wfu-amazons3-activation").classList.add("activating");var lbl=document.querySelector(".wfu-amazons3-activation .not-activated");lbl.innerHTML=lbl.getAttribute("data-activating")}
function wfu_amazons3_authorize_app_finish(nonce){var publickey=document.querySelector(".wfu-amazons3-keys .publickey").value;var privatekey=document.querySelector(".wfu-amazons3-keys .privatekey").value;if(publickey.trim()==""||privatekey.trim()=="")return;var xhr=wfu_GetHttpRequestObject();if(xhr==null)return;var url=AdminParams.wfu_ajax_url;params=new Array(3);params[0]=new Array(2);params[0][0]="action";params[0][1]="wfu_ajax_action_amazons3_authorize_app_finish";params[1]=new Array(2);params[1][0]=
"publickey";params[1][1]=publickey;params[2]=new Array(2);params[2][0]="privatekey";params[2][1]=privatekey;params[3]=new Array(2);params[3][0]="nonce";params[3][1]=nonce;var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);document.querySelector(".wfu-amazons3-keys button").disabled=true;document.querySelector(".wfu-amazons3-keys .error-message").classList.remove("visible");xhr.open("POST",url,true);xhr.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");xhr.onreadystatechange=function(){if(xhr.readyState==4)if(xhr.status==200){document.querySelector(".wfu-amazons3-keys button").disabled=false;var start_text="wfu_amazons3_authorize_app_finish:";var pos=xhr.responseText.indexOf(start_text);if(pos==-1)pos=xhr.responseText.length;var messages=xhr.responseText.substr(0,pos);var response=xhr.responseText.substr(pos+start_text.length,xhr.responseText.length-pos-start_text.length);if(response=="success")document.getElementById("editsettings").submit();
else{document.querySelector(".wfu-amazons3-keys .error-message").innerHTML=response;document.querySelector(".wfu-amazons3-keys .error-message").classList.add("visible");console.log("Amazon S3 application authorization error: "+response)}}};xhr.send(parameters)}
function wfu_amazons3_authorize_app_reset(nonce){var xhr=wfu_GetHttpRequestObject();if(xhr==null)return;var url=AdminParams.wfu_ajax_url;params=new Array(2);params[0]=new Array(2);params[0][0]="action";params[0][1]="wfu_ajax_action_amazons3_authorize_app_reset";params[1]=new Array(2);params[1][0]="nonce";params[1][1]=nonce;var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);xhr.open("POST",url,true);xhr.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");xhr.onreadystatechange=function(){if(xhr.readyState==4)if(xhr.status==200){var start_text="wfu_amazons3_authorize_app_reset:";var pos=xhr.responseText.indexOf(start_text);if(pos==-1)pos=xhr.responseText.length;var messages=xhr.responseText.substr(0,pos);var response=xhr.responseText.substr(pos+start_text.length,xhr.responseText.length-pos-start_text.length);if(response=="success")document.getElementById("editsettings").submit();else console.log("Amazon S3 application authorization reset error: "+
response)}};xhr.send(parameters)}
function wfu_amazons3_send_file(filepath_enc,ii){var xhr=wfu_GetHttpRequestObject();if(xhr==null)return;var nonce="";var nonce_elem=document.getElementById("wfu_amazons3_transfer_nonce");if(nonce_elem)nonce=nonce_elem.value;if(nonce=="")return;var url=AdminParams.wfu_ajax_url;params=new Array(2);params[0]=new Array(3);params[0][0]="action";params[0][1]="wfu_ajax_action_amazons3_add_file";params[1]=new Array(2);params[1][0]="file";params[1][1]=filepath_enc;params[2]=new Array(2);params[2][0]="nonce";
params[2][1]=nonce;var parameters="";for(var i=0;i<params.length;i++)parameters+=(i>0?"&":"")+params[i][0]+"="+encodeURI(params[i][1]);document.getElementById("wfu_send_to_amazons3_"+ii+"_a").href="javascript: void(0)";document.getElementById("wfu_send_to_amazons3_"+ii+"_img").style.display="inline";xhr.open("POST",url,true);xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhr.onreadystatechange=function(){if(xhr.readyState==4){document.getElementById("wfu_send_to_amazons3_"+
ii+"_img").style.display="none";if(xhr.status==200){var start_text="wfu_amazons3_add_file:";var pos=xhr.responseText.indexOf(start_text);if(pos==-1)pos=xhr.responseText.length;var messages=xhr.responseText.substr(0,pos);var response=xhr.responseText.substr(pos+start_text.length,xhr.responseText.length-pos-start_text.length);pos=response.indexOf(":");var txt_header=response.substr(0,pos);txt_value=response.substr(pos+1,response.length-pos-1);if(txt_header=="success")document.getElementById("wfu_send_to_amazons3_"+
ii+"_a").innerHTML=document.getElementById("wfu_send_to_amazons3_"+ii+"_inpok").value;else document.getElementById("wfu_send_to_amazons3_"+ii+"_a").innerHTML=document.getElementById("wfu_send_to_amazons3_"+ii+"_inpfail").value}}};xhr.send(parameters)};
